### ISSUE TITLE
Error when @Fixture used, Reflect Error: Decorator of type Property, Parameter applied into Method

### ISSUE THREAD

**Issue by riddhiparekh** [CyriacBr/class-fixtures-factory#12]
I am using `class-validator` to validate my classes and there are few issues I am running into while using `class-fixtures-factory` for test cases.
1. `FixtureFactory` is asking to define `@Fixture` for properties with `@IsOptional()` decorator.
2. When I use `@Fixture()` decorator to define type to be used, like in documentation for any properties, I am getting Following error.
```Reflect Error: Decorator of type Property, Parameter applied into Method```

Using NextJS with TypeScript.
Affecting Modules:
```
"next": "9.5.3"
"class-fixtures-factory": "^1.4.2"
"class-transformer": "^0.3.1"
"class-validator": "^0.11.1"
"reflect-metadata": "^0.1.13"
"jest": "^26.6.3"

node: v12.18.3
```

TS Config (Compiler Options):
```
"experimentalDecorators": true,
"emitDecoratorMetadata": true,
"target": "es5",
"lib": ["dom", "dom.iterable", "esnext"],
"allowJs": true,
"skipLibCheck": true,
"strict": false,
"forceConsistentCasingInFileNames": true,
"noEmit": false,
"esModuleInterop": true,
"module": "esnext",
"moduleResolution": "node",
"resolveJsonModule": true,
"isolatedModules": true,
"rootDir": "src",
"outDir": "dist",
```

Error Traces are as follow:
```
Server Error
Error: Reflect Error: Decorator of type Property, Parameter applied into Method

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
throwIfNotOfType
node_modules/tinspector/lib/index.js (232:19)
<unknown>
node_modules/tinspector/lib/index.js (259:9)
```

Thanks for the library and in Advance for helping out.

**Comment by CyriacBr** [comment]
I'll look into it this weekend if I can.

**Comment by riddhiparekh** [comment]
> I'll look into it this weekend if I can.

Hello Cyriac! Were you able to look into the issue?

**Comment by CyriacBr** [comment]
@riddhiparekh Could you provide the class you applied `isOptional`to?

**Comment by riddhiparekh** [comment]
@CyriacBr ,

````
export abstract class BaseEntity {
  @IsString()
  @IsOptional()
  legacyId?: string;

  @IsDate()
  @IsOptional()
  created: Date;

  @IsDate()
  @IsOptional()
  lastUpdated: Date;
}
export class Image extends BaseEntity {
  @IsString()
  @IsOptional()
  description?: string;

  @IsString()
  @IsOptional()
  title?: string;

  @IsString()
  @IsOptional()
  url: string;

  @IsNumber()
  @IsOptional()
  width?: number;

  @IsNumber()
  @IsOptional()
  height?: number;

}
```

**Comment by CyriacBr** [comment]
@riddhiparekh This should be fixed. Install the latest version. `class-fixtures-factory@latest`.

**Comment by riddhiparekh** [comment]
Hi @CyriacBr ,
Thanks so much for being such supportive. 
Issue with `@IsOptional` has been resolved.
There were two reported issues,
I checked `@Fixture` and it is still not usable, can you help out with that?

While using `@Fixture({ignore: true})` for following Property I am getting Error.
Reflect Error: Decorator of type Property, Parameter applied into Method.
Just adding this property in our above `Image` class will throw error.
```
  @IsJSON()
  @IsOptional()
  @Fixture({ ignore: true })
  sizes?: {};
```

Thanks again.

**Comment by CyriacBr** [comment]
@riddhiparekh I cannot reproduce the issue. May be due to your project's environment. Can you provide a small reproduction?

**Comment by riddhiparekh** [comment]
@CyriacBr 
I have reproduced the issue and have pushed setup [here](https://github.com/riddhiparekh/fixture-factory-issue)

After `npm install`, execute `npm run test` for test case.
Test case is located in `tests/creator.test.ts` and Validator class at `Image.ts`.
Thanks.

**Comment by CyriacBr** [comment]
There's an incompatibility issue between `babel` and `tinspector`. This'd require further investigations.
