### ISSUE TITLE
Example of using it with class-validator and DI (if required)

### ISSUE THREAD

**Issue by nolazybits** [CyriacBr/class-fixtures-factory#2]
I really like the fact you are leveraging existing class-validator.
I've been trying to have data generated for a model like this for instance

```
import { Fixture } from "class-fixtures-factory";
import { IsString } from "class-validator";

export abstract class ITest
{
    @IsString()
    public abstract name: string;

    @Fixture()
    public abstract age: number;
}
```

Sadly the name property is not generated. Only the one with the `Fixture` decorator.
Would you have a working example somewhere I could look at or is this a bug?

Do I need to map the class-validator metadataStore to the one used by this library at all?

Thanks for the library!

**Comment by CyriacBr** [comment]
Hello.
I actually forgot to support some of the basic `class-validator` decorators such as `IsString`. I just pushed an update and that should work for now, thanks for letting me know!

However, keep in mind that I was wondering about a more efficient way to handle third-party decorators, so there may be missing support for some other decorators too. Feel free to let me know if there are other decorators from `class-validator` I should support.

Also I updated the README so you should read it again.

**Comment by nolazybits** [comment]
Thank you much for the fast answer.
I'll keep you posted and happy to create PRs too!
Thanks again.

**Comment by nolazybits** [comment]
I'm sorry but this same example is still not working with the new released version.

**Comment by nolazybits** [comment]
One thing is class-validator has been updated to 0.12.x where changes were introduce to the metadata store and how to get it. That might be the why? Would be good to add version range in your package.json on the class-validator 0.11.x and maybe (please) have a 1.5 version supporting class-validator >= 0.12.x

Thanks a lot!

**Comment by CyriacBr** [comment]
Yeah I updated class-validator and my tests break now. I'll have to look into that.
Thank you.

**Comment by CyriacBr** [comment]
So, it appears that since the 0.12 version, the decorators names are lost when stored. [I opened and issue there](https://github.com/typestack/class-validator/issues/622).

So, unless they fix that, there'd be no way to know which decorators are used in your classes. So if you want to use `class-fixtures-factory`, you'd have to rollback to 0.11.x version. I'll add a disclaimer in the README.

**Comment by nolazybits** [comment]
I hope they'll fix this in class-validator🤞
Thanks again @CyriacBr for being so reactive 👍

**Comment by nolazybits** [comment]
@CyriacBr we have forked class-validator here
https://github.com/ts-revival/class-validator

if you could provide maybe a version that uses @ts-revival/class-validator so we can start moving forward that would be awesome!

Thanks for this awesome lib again

**Comment by CyriacBr** [comment]
Hi @nolazybits . Sorry for the late reply, was kinda busy.
I'm going to look into a new release for this package next weekend so hopefully I'll see how to integrate your fix.
